"""empty message

Revision ID: 778ee797d56a
Revises: None
Create Date: 2016-09-01 18:22:53.621258

"""

# revision identifiers, used by Alembic.
revision = '778ee797d56a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('proxy', sa.String(length=64), nullable=True),
    sa.Column('system', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('monitor', sa.Boolean(), nullable=True),
    sa.Column('i_time', sa.DateTime(), nullable=True),
    sa.Column('i_user', sa.String(length=64), nullable=True),
    sa.Column('data', sa.Text(length=65535), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_dns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('domain_name', sa.String(length=64), nullable=True),
    sa.Column('domain_type', sa.String(length=64), nullable=True),
    sa.Column('domain_add', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=True),
    sa.Column('game_name', sa.String(length=64), nullable=True),
    sa.Column('game_lange', sa.String(length=64), nullable=True),
    sa.Column('game_static', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_fault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fault_date', sa.DateTime(), nullable=True),
    sa.Column('fault_describe', sa.Text(length=65535), nullable=True),
    sa.Column('fault_range', sa.String(length=64), nullable=True),
    sa.Column('fault_impact_time', sa.String(length=64), nullable=True),
    sa.Column('fault_user_experience', sa.Boolean(), nullable=True),
    sa.Column('fault_affect_user', sa.String(length=64), nullable=True),
    sa.Column('fault_economic_losses', sa.String(length=64), nullable=True),
    sa.Column('fault_data_form', sa.String(length=64), nullable=True),
    sa.Column('fault_core_business', sa.Boolean(), nullable=True),
    sa.Column('fault_business_module', sa.String(length=64), nullable=True),
    sa.Column('fault_operations_center', sa.String(length=64), nullable=True),
    sa.Column('fault_type', sa.String(length=64), nullable=True),
    sa.Column('fault_head', sa.String(length=64), nullable=True),
    sa.Column('fault_attribution', sa.String(length=64), nullable=True),
    sa.Column('fault_status', sa.Boolean(), nullable=True),
    sa.Column('fault_cause_problem', sa.Text(length=65535), nullable=True),
    sa.Column('fault_clusion', sa.Text(length=65535), nullable=True),
    sa.Column('fault_improve', sa.Text(length=65535), nullable=True),
    sa.Column('fault_app_type', sa.String(length=64), nullable=True),
    sa.Column('fault_month', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('ssh_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('history', sa.Text(length=65535), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_table('ssh_history')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('report_fault')
    op.drop_table('report_dns')
    op.drop_table('machine')
    ### end Alembic commands ###
